server:
  port: 9001

spring:
  application:
    name: MOVIE-SERVICE
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://movieservicedb:5432/postgres
    username: postgres
    password: group6

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://serviceregistry:8761/eureka/