server:
  port: 9002


spring:
  application:
    name: REVIEW-SERVICE
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/review_service_db
    username:
    password: 

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost